### ISSUE TITLE
Backstop: Claim into backstop

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#141]
The current backstop claim function sends earned BLND tokens directly to the user.

There is a TODO in code that states:
```
// TODO: Deposit emissions back into the backstop automatically after 80/20 BLND deposit function added
```

A decision needs to be made where claimed funds will go, and how they will get there, then implemented.

### Technical notes

In the event this direction is chosen, it would be smart to test if the backstop can mint LP tokens on behalf of the user with their earned BLND, and have them end up in the backstop, and crediting the user backstop deposit said amount for that pool. However, there is some concern about resource limits here.

**Comment by markuspluna** [comment]
resolved in
https://github.com/blend-capital/blend-contracts/pull/142
