### ISSUE TITLE
BL-002 - Integer underflow in auction scaling mechanism

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#160]
The auction logic sets the start block to `cur_block + 1`, causing a potential underflow if the auction is filled on the same block, which could result in a loss of capital for the liquidated user.

This is currently blocked by a build configuration, but either checked math and/or tests need to be added to ensure a build configuration change does not break this assumption.

**Comment by markuspluna** [comment]
Resolved in 
https://github.com/blend-capital/blend-contracts/pull/173
Opted to add tests to confirm that an underflow and overflow flags work as intended

**Comment by markuspluna** [comment]
173 merged
