### ISSUE TITLE
BL-014 - Incorrect bounds check of reactivity constant in require_valid_reserve_metadata

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#166]
Inconsistency in white paper and code about the reactivity constant bounds.

Either contracts or whitepaper need to be fixed.

**Comment by mootz12** [comment]
cc @markuspluna 

Looks like the whitepaper advocates for the reactivity constant to have `[10e-6, 10e-4]` as bounds. The lower bound is a mistake in the whitepaper, as we don't really care how low a pool sets this (and even have thought of plenty of use cases where turning this off, IE setting it to 0).

This was a number I came up with awhile back, and it was derived such that a a 80% target utilization asset, if fully borrowed, would hit the IR modifier maximum (10x) in 1 month. I figured anything more extreme than that was too quick. Also, the downside of this is generally more extreme (more room for delta target utilization).

 -> 17280 blocks a day * 30 days * 10e^-4 reactivity * 0.2 delta target utilization = 10.3

This being said, the code also is calculation this off of timestamp, which will be about 5x quicker. This means a similar reactivity constant bound would be `2e^-5` as the maximum bound.

My questions to you are:
1. Do you see any issues calculating this with timestamp instead of blocks? We accrue interest over timestamps, but this would me the rate modifier would change if the chain stalled.
2. Thoughts on proposed upper bound? I know you did some additional liquidation related testing awhile back.

**Comment by markuspluna** [comment]
1. I think blocks are safer with no real downside
2. I'd 5x the reactivity constant upper bound. We only care about preventing settings from being completely stupid - 50x in a month is pretty dang stupid but not completely

**Comment by mootz12** [comment]
> 1. I think blocks are safer with no real downside

Note - I opted to retain the timestamp based calculation. The main reason being I don't think the marginally safer situation with blocks is worth storing the extra "last_block" value on the reserve data object.
