### ISSUE TITLE
BLRC-002 - Potential pitfalls in reserve loading and caching mechanism

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#168]
Potential for developer misuse for the writeback pattern with the reserve cacheing mecahnism.

Suggestion to add a drop guard pattern in which the reserve structure is validated to have been written back to storage unless it has been explicitly “defused”.

**Comment by cristian9890ji-alt** [comment]
Ayuda

**Comment by cristian9890ji-alt** [comment]
Ayuda

**Comment by cristian9890ji-alt** [comment]
Ayuda
