### ISSUE TITLE
Different APY 

### ISSUE THREAD

**Issue by reigister** [blend-capital/blend-contracts#190]
Different APY
at above show 0,37% for wBTC
but in below show only 0,15% for wBTC
<img width="500" alt="Screenshot 2024-02-12 234421" src="https://github.com/blend-capital/blend-contracts/assets/78670969/7e7cef18-748a-4b48-a1b8-9bfa5261dc3d">

**Comment by markuspluna** [comment]
Thanks! The APY being displayed should be the average supplied position APY, however it looks like it's showing the borrow apy. Since this is a UI issue we'll track it here
https://github.com/blend-capital/blend-ui/issues/82
