### ISSUE TITLE
Backstop Interest Likely Lost to Gas

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#31]
When backstop interest is auctioned off, the filler will only buy the interest if the spread they make is greater than the gas cost they have to spend.

If backstop interest auctions are small, this means that a significant portion of the interest earned will be used to cover gas costs, cutting into the amount earned by the backstop.

Consider a mechanism to stop this from happening.

**Comment by markuspluna** [comment]
Closing - handled and discussed in PR #95
