### ISSUE TITLE
Consider tracking rates with 12 decimals

### ISSUE THREAD

**Issue by mootz12** [blend-capital/blend-contracts#84]
Currently, d_rate is tracked with 9 decimals. When calculating this, the protocol is rounding up to avoid a situation in which the reserve can not accrue at all.

Consider tracking the rates with 12 decimals to avoid any excess interest accrual as a result of rounding up.

**Comment by markuspluna** [comment]
is there any downside to doing 12 decimals?

**Comment by mootz12** [comment]
The risk of overflow is most likely to occur when computing "totalSupply" or "totalLiabilities" with fixed point math, which is:

~= (protocol_tokens * protocol_token_rate) / 10^rate_decimals

Depending on how many decimals the protocol token is tracked in, that leaves a cap on the number of protocol tokens we can issue (protocol tokens are tracked at the same precision as the underlying asset).

So the approximate max total supply can be calculated assuming a max rate of 10: ~= 10^(38 - r - 1 - d)

Where r = 12 decimals and d is the underlying decimals listed below:
* 18 decimals
    * 10,000,000 max total supply
* 12 decimals
    * 10^13 -> 10,000,000,000,000 max total supply
* 7 decimals
    * 10^18 max total supply

Where r = 9 and d is the underlying decimals listed below:
* 18 decimals
    * 10^10 -> 10,000,000,000 max total supply
* 12 decimals
    * 10^16 max total supply
* 7 decimals
    * 10^21 max total supply

**Comment by markuspluna** [comment]
I think it's probably smartest to just stick with Stellar classic's decimal limits - which max out at 10^18 7 decimal - So I think we're likely good with 12 decimals

**Comment by markuspluna** [comment]
<img width="417" alt="image" src="https://github.com/blend-capital/blend-contracts/assets/59978114/34a21633-5659-4ba8-af1e-edc0156e991a">


Precision with different decimal places at 5% interest, compounding 10000 times and 1000 times. Honestly I think 9 is precise enough

**Comment by markuspluna** [comment]
https://github.com/script3/rounding-testing
